includes: 
  - !include configs/main/common/common.yml

main: DQN
agent: DQN

model-save-path: models
n-frames: 240000
evaluate-interval: 12000
dqn-replay-size: 8000
dqn-hidden-size: 32
#learning-rate: 0.1
dqn-batch-size: 30
gamma: 0.8
dqn-initial-eps: 0.9
dqn-final-eps: 0.02
dqn-explore-len-frac: 0.3
dqn-net-update-freq: 5
