ROADNET_FILE: data/roadnet.json
FLOW_FILE: data/flow.json
SAVEREPLAY: True
INTERVAL: 1.0
MIN_ACTION_TIME: 10
YELLOW_TIME: 5
DEACTIVATE_TIME: 300
ACTION_PATTERN: set
DEBUG: True
EPISODE_LEN: 3600
LIST_STATE_FEATURE: 
  - cur_phase
  - lane_num_vehicle
REWARD_INFO: 
  AVERAGE_FLOW_VEHICLE_COUNT: 0.03333
  # AVERAGE_WAIT_VEHICLE_COUNT: 0.03333
  # AVERAGE_INTERSECTION_PRESSURE: 0.03333
  # AVERAGE_ROADLINK_PRESSURE: 0.03333
  # AVERAGE_LANELINK_PRESSURE: 0.03333
DELTA_REWARD: False
DELTA_REWARD_MULTIPLIER: 500
